### ISSUE TITLE
Error In Displaying Page

### ISSUE THREAD

**Issue by zs5cey** [dg9vh/MMDVMHost-Dashboard#22] opened 2016-06-24 20:10 UTC
I am getting the following error in the logfile with the latest build:

[Fri Jun 24 22:07:27.947670 2016] [:error] [pid 25893] [client 192.168.100.201:58597] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:299\nStack trace:\n#0 /var/www/html/include/functions.php(299): DateInterval->__construct('PTS')\n#1 /var/www/html/include/repeaterinfo.php(15): getActualMode(Array, Array)\n#2 /var/www/html/index.php(42): include('/var/www/html/i...')\n#3 {main}\n  thrown in /var/www/html/include/functions.php on line 299, referer: http://192.168.100.60/

**Comment by dg9vh** [comment] 2016-06-24 20:20
@zs5cey this has something to do with the new parameters Jonathan put into the MMDVM.ini (several HangTimes...),

I am on vacation till Sunday Evening so I am not able to do something before Monday. I don't have access to my development environment at the moment. You can fix it yourself by replacing line 298
$hangtime = getConfigItem("General", "ModeHang", $mmdvmconfigs);
with
$hangtime = getConfigItem("General", "RFModeHang", $mmdvmconfigs);

On Monday I could do some further testing to detect if it was Net or RF and take the correct HangTime from MMDVM.ini.

**Comment by zs5cey** [comment] 2016-06-24 20:27
Hi Kim,

Thanks for the very fast response. No rush, you enjoy your holiday and I will make the change you suggest.

Andy

Get Outlook for Android

From: Kim - DG9VH

Sent: Friday, 24 June, 22:20

Subject: Re: [dg9vh/MMDVMHost-Dashboard] Error In Displaying Page (#22)

To: dg9vh/MMDVMHost-Dashboard

Cc: Andy, Mention

@zs5cey this has something to do with the new parameters Jonathan put into the MMDVM.ini (several HangTimes...),

I am on vacation till Sunday Evening so I am not able to do something before Monday. I don't have access to my development environment at the moment. You can fix it yourself by replacing line 298

$hangtime = getConfigItem("General", "ModeHang", $mmdvmconfigs);

with

$hangtime = getConfigItem("General", "RFModeHang", $mmdvmconfigs);

On Monday I could do some further testing to detect if it was Net or RF and take the correct HangTime from MMDVM.ini.

**Comment by dg9vh** [comment] 2016-06-24 20:38
@zs5cey Well. I have to do some checkings which version of MMDVMHost (or better, what version of MMDVM.ini) one is using. Moving blindly to the new structure would break all dashboards running on non-updated MMDVMHosts :-1: So first I have to check, if the ModeHang is present as config-option and if not, I have to check the source of the transmission to get the correct hangtime. Not a very big thing but to much to be done without testing. So it would be recommended to use the "hotfix" meanwile and then, when I fixed the issue, to do a

```
  git stash
  git pull
```

to get the actual clone from github again.

**Comment by dg9vh** [comment] 2016-06-27 14:56
Fixed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/59649948d3d3bd149acc905951f59a3b30dc72c8

**Closed as completed by dg9vh** 2016-06-27 14:56 UTC
Labels: bug

**Comment by s-s-s** [comment] 2020-02-03 14:11
For two days I searched for the cause of the dashboard failure )
