### ISSUE TITLE
Talker Alias not displayed

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#205] opened 2020-05-16 16:15 UTC
Hi everyone.
I configured a new MMDVM system and installed the dashboard.
In the log I see the data of the Talker Alias, but in the dashboard they do not appear, although the Show Talker Alias parameter is active.
Can you suggest me where I went wrong?
Thanks
'73 de Adam, IK4NZD
![Immagine1](https://user-images.githubusercontent.com/29512684/82124738-40264480-97a1-11ea-8c31-e66015a9a3e5.jpg)
![Immagine2](https://user-images.githubusercontent.com/29512684/82124739-40bedb00-97a1-11ea-8f70-38f9ee059630.jpg)

**Comment by dg9vh** [comment] 2020-05-16 17:24
Hi, I have to investigate it... Maybe there is some log-format change within the log-file...
What loglevels are you running?

**Comment by ik4nzd** [comment] 2020-05-16 19:49
I currently have DisplayLevel = 1 and FileLevel = 2.
I also tried with both at 1, but nothing changes.
I am using the latest versions of MMDVM and MMDVMHost (branch FM_Ext).
I am available if you need to test.
'73 de Adam

**Comment by ik4nzd** [comment] 2020-05-16 20:44
Now trying with levels 2 and 2.
The situation is always the same, no Talker Alias on the dashboard.
'73 de Adam, IK4NZD

**Comment by dg9vh** [comment] 2020-05-16 22:36
Tried with 1 and 1?

**Comment by ik4nzd** [comment] 2020-05-17 07:43
I had already tried with both values at 1.
These are the images.
![Immagine](https://user-images.githubusercontent.com/29512684/82138715-d0589e00-9822-11ea-8207-31f06735a796.jpg)
![Immagine1](https://user-images.githubusercontent.com/29512684/82138716-d0f13480-9822-11ea-8787-f9c3bb1d0d69.jpg)
A new FindWithName parameter exits, but the Talker Alias is not reported in the dashboard anyway

**Comment by dg9vh** [comment] 2020-06-03 18:15
Could you send me a logfile of your hotspot to take a look at it locally here on my dev-system?
email is dg9vh at darc point de

**Comment by ik4nzd** [comment] 2020-06-03 20:19
Mail send now

**Comment by dg9vh** [comment] 2020-06-03 20:30
not received yet... sure it was right address? dg9vh [at] darc [.] de

**Comment by dg9vh** [comment] 2020-06-03 20:35
I sent you an email to your qrz.com listed address with other mailaddress - use that instead of this above... maybe darc has problems with some kind of attachements.

**Comment by dg9vh** [comment] 2020-06-05 18:10
Hi, I solved the problem now - just get an actual version of the dashboard :-) The problem is fixed in functions.php

**Closed as completed by dg9vh** 2020-06-05 18:10 UTC
