### ISSUE TITLE
Dashboard doesn't show connected reflector if connecting with late entry into over.

### ISSUE THREAD

**Issue by dc7jzb** [dg9vh/MMDVMHost-Dashboard#39] opened 2016-09-08 06:52 UTC
I don't know really that it is an issue in the Dashboard.
Since the last update of MMDVMHost (compiled yesterday) the Dashboard doesn't Show the actually connected Reflector. It only shows TG9/Reflector not connected.
Traffic from the connected Reflector comes normal, and the Dashboard of the Network (BM) shows it too.
Terminal Output of MMDVMHost looks normal.
Before update it showed right. (checked with an older copy of that Image without the last update)

**Comment by dg9vh** [comment] 2016-09-08 06:56
Hi,
what network are you connected to? DMRPlus or BrandMeister or something else?

**Comment by dg9vh** [comment] 2016-09-08 06:59
Ok, I saw within your text you mentioned BM... have to check it this evening...

**Comment by dg9vh** [comment] 2016-09-08 15:58
Can't reproduce, what loglevels have you set?

**Comment by dc7jzb** [comment] 2016-09-08 18:24
Looked in the ini:

Display Level:1
File Level:2

Am Donnerstag, 8. September 2016 schrieb Kim - DG9VH :

**Comment by dg9vh** [comment] 2016-09-08 18:32
@dc7jzb what hardware are you using? MMDVM or DVMEGA?

**Comment by dc7jzb** [comment] 2016-09-08 18:33
I have changed the Loglevel to
Display Level:2
File Level:2

Now it works fine.
I'am only wondering, because I have took the old ini file without changes.

But now it shows all right.

73 Mario

Am Donnerstag, 8. September 2016 schrieb Timelord Der Hexer :

**Comment by dg9vh** [comment] 2016-09-08 18:35
There must be an issue with MMDVMHost and it's logging - normally FileLevel=2 and DisplayLevel=whateveryouwant should work. I did not test this in my setup with different values, but this is not an Issue of the dashboard then.

I close this issue now because of no action required by me.

**Comment by dg9vh** [comment] 2016-09-08 18:39
I now see an issue when doing a late-entry into a BM-Reflector - then no parrot-announcement is following but you hear the talking person... so the dashboard could not detect the confirmation of linkage... maybe I should detect only the link-request by the radio and not the confirmation by the parrot...

**Comment by dg9vh** [comment] 2016-09-08 19:46
finally closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/bb21c7ec9daa5f5cdb58a09ffae280828bc5521c

**Closed as completed by dg9vh** 2016-09-08 19:46 UTC
Labels: bug
